### ISSUE TITLE
Add a Search Option in Navbar

### ISSUE THREAD

**Issue by diyajaiswal11** [diyajaiswal11/Bloggitt#1]
Add a simple search bar in the navbar and write corresponding urls.py and views.py to search posts based on its title and content.

**Comment by yashgautam9274** [comment]
I want to work on this issue

**Comment by diyajaiswal11** [comment]
Sure @yashgautam9274 , Go ahead.

**Comment by yashgautam9274** [comment]
I solve the issue . I send Pull request on 1 dec

**Comment by yashgautam9274** [comment]
can u guide how i add urls.py and views.py to search posts based on its title and content

**Comment by diyajaiswal11** [comment]
> can u guide how i add urls.py and views.py to search posts based on its title and content

You'll be making a function in views.py which will take a query parameter from user ( name it **query**, for example). Then you'll filter post objects using title__icontains=**query** and content__icontains=**query** and display the objects after applying filter.

**Comment by friskycodeur** [comment]
Can you assign this to me , thanks !

**Comment by diyajaiswal11** [comment]
> Can you assign this to me , thanks !

Sure @friskycodeur , Go ahead.

**Comment by prakhar1144** [comment]
Can you assign this to me, thanks !
