### ISSUE TITLE
Redirect to django admin from site login

### ISSUE THREAD

**Issue by SubhradeepSS** [diyajaiswal11/Bloggitt#10]
If a superuser enters his credentials in our login page, then the django admin will open instead of the normal homepage(which is opening for other normal users).

**Comment by SubhradeepSS** [comment]
@diyajaiswal11 i was thinking of working on this issue, can u please it to me?

**Comment by diyajaiswal11** [comment]
Hey @SubhradeepSS , I don't find this to be a valid issue, as a superuser can also visit the website like normal users and if he wants to login through admin, he can do that too easily.
