### ISSUE TITLE
Add content in about.html

### ISSUE THREAD

**Issue by diyajaiswal11** [diyajaiswal11/Bloggitt#13]
View the category details in #7 , and write a 5-6 line content for about.html and make it exactly the same as index.html.

**Comment by subhangi2731** [comment]
can you please assign this issue to me? @diyajaiswal11

**Comment by diyajaiswal11** [comment]
Sure @subhangi2731 , Go ahead.

**Comment by vickova** [comment]
Please can you assign thid issue to me?

**Comment by diyajaiswal11** [comment]
> Please can you assign thid issue to me?

Hey @vickova , if @subhangi2731 does not make a PR within 3 days from now, I'll assign it to you. Meanwhile you can check other unassigned issues.

**Comment by Bansi32** [comment]
Please can you assign thid issue to me?

**Comment by Bansi32** [comment]
can you please assign this issue to me?

**Comment by diyajaiswal11** [comment]
> can you please assign this issue to me?

Hey @Bansi32 , Issues will be assigned on first come,first server basis. As this issue has already been assigned, you can check other unassigned issues.

**Comment by Halix267** [comment]
Since there is no update in this issue so can I work on this  @diyajaiswal11

**Comment by yashgautam9274** [comment]
I want to work on this issue

**Comment by diyajaiswal11** [comment]
> I want to work on this issue

Go ahead @yashgautam9274

**Comment by yashgautam9274** [comment]
can you elaborate the issue

**Comment by rsrkpatwari1234** [comment]
Hey @diyajaiswal11 !! Can you please assign this issue to me ?

**Comment by diyajaiswal11** [comment]
> Hey @diyajaiswal11 !! Can you please assign this issue to me ?

Go ahead @rsrkpatwari1234
