### ISSUE TITLE
Add Like option on Blog posts

### ISSUE THREAD

**Issue by diyajaiswal11** [diyajaiswal11/Bloggitt#16]
User should be able to like the blog posts.
- Add a like button on each blog post card.
- Write backend code for updating likes on the blog post.

**Comment by SubhradeepSS** [comment]
@diyajaiswal11 I would like to work on this issue. Can u assign it to me?

**Comment by diyajaiswal11** [comment]
> @diyajaiswal11 I would like to work on this issue. Can u assign it to me?

Sure @SubhradeepSS . Go ahead.

**Comment by tejaswini22199** [comment]
hey @diyajaiswal11  can you assign me if no one is working

**Comment by diyajaiswal11** [comment]
> hey @diyajaiswal11 can you assign me if no one is working

Sure @tejaswini22199 , Go ahead.

**Comment by tejaswini22199** [comment]
hey what are the credentials that we need to use for login??

**Comment by diyajaiswal11** [comment]
> hey what are the credentials that we need to use for login??

You can create a superuser and a normal user for your testing purpose. We are not pushing db.sqlite3 so as to keep the database clean.

**Comment by SubhradeepSS** [comment]
@diyajaiswal11 Can i also work on this issue?

**Comment by diyajaiswal11** [comment]
> @diyajaiswal11 Can i also work on this issue?

Hey @SubhradeepSS , if @tejaswini22199  does not make a PR within 3 days from now, I'll assign it to you.

**Comment by SubhradeepSS** [comment]
> 
> 
> > @diyajaiswal11 Can i also work on this issue?
> 
> Hey @SubhradeepSS , if @tejaswini22199 does not make a PR within 3 days from now, I'll assign it to you.

@diyajaiswal11 If @tejaswini22199 is not working on the issue, can it be assigned to me?

**Comment by TrushaT** [comment]
Since both @SubhradeepSS @tejaswini22199  have been given chance once,if no PR is created I would like to be assigned this task please @diyajaiswal11

**Comment by diyajaiswal11** [comment]
> Since both @SubhradeepSS @tejaswini22199 have been given chance once,if no PR is created I would like to be assigned this task please @diyajaiswal11

Sure @TrushaT , Go ahead.
