### ISSUE TITLE
Add to Favorite Option

### ISSUE THREAD

**Issue by diyajaiswal11** [diyajaiswal11/Bloggitt#17]
User should be able to save his favorite blog posts.
- Add an icon that allows users to add a blog post to his favorites or remove from the same.
- Create a separate page that displays the favorite blog posts of logged in user.

**Comment by SubhradeepSS** [comment]
@diyajaiswal11 I would like to work on this issue. Can u assign it to me?

**Comment by diyajaiswal11** [comment]
> @diyajaiswal11 I would like to work on this issue. Can u assign it to me?

Hey @SubhradeepSS , please don't start working on an issue unless it's assigned to you.

**Comment by SubhradeepSS** [comment]
> 
> 
> > @diyajaiswal11 I would like to work on this issue. Can u assign it to me?
> 
> Hey @SubhradeepSS , please don't start working on an issue unless it's assigned to you.

Sorry. will keep that in mind from next time.
