### ISSUE TITLE
Add About Page

### ISSUE THREAD

**Issue by diyajaiswal11** [diyajaiswal11/Bloggitt#2]
Add an about.html file and link it with the about button on navbar.

**Comment by yashgautam9274** [comment]
Please assign this issue to me

**Comment by diyajaiswal11** [comment]
Hey @tejaswini22199 , make sure that the issue is assigned to you before you start working on it, So that I know who is working on which issue. Take care next time. 
Hey @yashgautam9274 , as @tejaswini22199 is working on this issue, I'll assign the issue #1 to you.

**Comment by tejaswini22199** [comment]
sure @diyajaiswal11 and sorry for creating pull request before assigning it to me

**Comment by tejaswini22199** [comment]
can u assign it to me now @diyajaiswal11  and review my pull request

**Comment by diyajaiswal11** [comment]
Sure @tejaswini22199 .
