### ISSUE TITLE
Add View Count + Read Time Feature

### ISSUE THREAD

**Issue by diyajaiswal11** [diyajaiswal11/Bloggitt#25]
- Add a View Count feature that will display the number of times any Blog Post has been viewed. 
- On the index.html page, each post should have an eye icon along with an integer that displays the number of views on that post.
- Add a Read Time feature that calculates the read time of any post and displays it on the UI, similar to that on medium.com

**Comment by SubhradeepSS** [comment]
@diyajaiswal11 for the no of views on a post, i was thinking of adding an additional attribute for blog model which will store the no. of views and increment it by 1 every time, post_detail request is made.
what do you think is it a good idea to work for this issue?

**Comment by SubhradeepSS** [comment]
@diyajaiswal11 i would like to work for this issue

**Comment by SubhradeepSS** [comment]
@diyajaiswal11 Can u assign me this issue?

**Comment by SubhradeepSS** [comment]
@diyajaiswal11 For the read time feature, will the author of the blog set the read time, or will it be automatically generated(using some other package)?

**Comment by diyajaiswal11** [comment]
> @diyajaiswal11 For the read time feature, will the author of the blog set the read time, or will it be automatically generated(using some other package)?

Sure @SubhradeepSS , Go ahead.

**Comment by diyajaiswal11** [comment]
> @diyajaiswal11 For the read time feature, will the author of the blog set the read time, or will it be automatically generated(using some other package)?

@SubhradeepSS , You can use this -  _from .utils import get_read_time_ . Please study about this, and let me know if you've a doubt.
