### ISSUE TITLE
Add Forgot Password Feature

### ISSUE THREAD

**Issue by diyajaiswal11** [diyajaiswal11/Bloggitt#26]
- Currently, there is no option for resetting the password in case the user forgot it.
- Add the "forgot password" functionality via sending mail at registered email-id to reset it.
- The Login Page should have an option of Forgot Password that will redirect user to Forgot Password page.
- Template should be same as Signup and Login Page.

**Comment by SubhradeepSS** [comment]
@diyajaiswal11 I want to work on this issue. Can u assign it to me?

**Comment by diyajaiswal11** [comment]
> @diyajaiswal11 I want to work on this issue. Can u assign it to me?

Sure @SubhradeepSS , Go ahead.

**Comment by SubhradeepSS** [comment]
@diyajaiswal11 do we need to currently send to the exact email or we can use `django.core.mail.backends.console.EmailBackend` for development purposes, which will send the reset link to the cli?
