### ISSUE TITLE
Enhance the UI of the Project

### ISSUE THREAD

**Issue by diyajaiswal11** [diyajaiswal11/Bloggitt#29]
The current UI of the project is very simple. Design and integrate a new UI for the project that suits well with the topic and looks interactive.
You can use HTML, CSS, Javascript or any CSS Framework as per your choice and preference.

**Comment by prakhar1144** [comment]
Hi please assign it to me. Thanks!

**Comment by diyajaiswal11** [comment]
> Hi please assign it to me. Thanks!

Sure @prakhar1144 , Go ahead.
