### ISSUE TITLE
Image Upload Feature in Blog

### ISSUE THREAD

**Issue by diyajaiswal11** [diyajaiswal11/Bloggitt#3]
Add the Image upload feature while posting a Blog.

**Comment by Halix267** [comment]
@diyajaiswal11 I would like to work on the issue for NWOC. Would you like to assign it to me?

**Comment by diyajaiswal11** [comment]
Sure @Halix267 , Go ahead.

**Comment by SubhradeepSS** [comment]
@diyajaiswal11 can i work on this issue since there is not PR for 7days?

**Comment by diyajaiswal11** [comment]
> @diyajaiswal11 can i work on this issue since there is not a PR for 7days?

Sure @SubhradeepSS , Go ahead.
