### ISSUE TITLE
Add comments to each blog

### ISSUE THREAD

**Issue by Vrindagupta6828** [diyajaiswal11/Bloggitt#37]
We can add comment section so that any user can comment his/her views on a specific blog

**Comment by diyajaiswal11** [comment]
> We can add comment section so that any user can comment his/her views on a specific blog

That's a great idea. Would you like to work on this issue? @Vrindagupta6828

**Comment by Vrindagupta6828** [comment]
Yes sure

**Comment by diyajaiswal11** [comment]
> Yes sure

Sure @Vrindagupta6828 , Go ahead.

**Comment by Vrindagupta6828** [comment]
@diyajaiswal11  Please give me points for raising an issue

**Comment by SubhradeepSS** [comment]
@diyajaiswal11 Can i work on this issue?

**Comment by Vrindagupta6828** [comment]
@SubhradeepSS i am working on this issue
