### ISSUE TITLE
Bug: requirements.txt file

### ISSUE THREAD

**Issue by SubhradeepSS** [diyajaiswal11/Bloggitt#45]
**Describe the bug**
The **requirements.txt** file in the main repo is not having all the packages used by the project.

**Comment by SubhradeepSS** [comment]
@diyajaiswal11 shall i add all the required packages to the requirements.txt file and make a PR?

**Comment by diyajaiswal11** [comment]
> @diyajaiswal11 shall i add all the required packages to the requirements.txt file and make a PR?

Sure @SubhradeepSS
