### ISSUE TITLE
Add User Authentication

### ISSUE THREAD

**Issue by diyajaiswal11** [diyajaiswal11/Bloggitt#5]
- User should enter his email, username and password to Register.
- To Login, he should enter his email and password. 
- Add the templates for the same. (Make a similar page as that of detail.html and inside the container add the forms for login and signup. 
- Also add signup, login and logout options accordingly in the navbar.

**Comment by SubhradeepSS** [comment]
@diyajaiswal11 I would like to work on the issue for NWOC'20. Would you like to assign it to me?

**Comment by diyajaiswal11** [comment]
Sure @SubhradeepSS , Go ahead.

**Comment by SubhradeepSS** [comment]
> 
> 
> Sure @SubhradeepSS , Go ahead.

Can we use the default username and password authentication for login?

**Comment by diyajaiswal11** [comment]
You've to use _from django.contrib.auth.models import User_ for authentication.

**Comment by SubhradeepSS** [comment]
> 
> 
> You've to use _from django.contrib.auth.models import User_ for authentication.

actually I was asking about using only username and password for login, instead of email and password.

**Comment by diyajaiswal11** [comment]
> > Sure @SubhradeepSS , Go ahead.
> 
> Can we use the default username and password authentication for login?

You've to use _from django.contrib.auth.models import User_ for authentication.

**Comment by diyajaiswal11** [comment]
> > You've to use _from django.contrib.auth.models import User_ for authentication.
> 
> actually I was asking about using only username and password for login, instead of email and password. django's default auth uses username and password

Yaa got it, Yes you can do it.
