### ISSUE TITLE
Beautify the add comment section

### ISSUE THREAD

**Issue by Vrindagupta6828** [diyajaiswal11/Bloggitt#52]
The comments and the form fir the same is not that beautiful and neat.

Use some CSS and bootstrap files to beautify the comment section

**Comment by sayna3311** [comment]
I would like to try it out? Can you please assign this to me?

**Comment by diyajaiswal11** [comment]
@Vrindagupta6828 and @sayna3311 , let me know which one of you will be working on this issue.

**Comment by sayna3311** [comment]
Please, assign this to me. I will work on it @diyajaiswal11 .

**Comment by Vrindagupta6828** [comment]
@diyajaiswal11 since i have raised the issue i would like to work on it

**Comment by Vrindagupta6828** [comment]
@diyajaiswal11 Have you given me points for raising this pr?

**Comment by diyajaiswal11** [comment]
> @diyajaiswal11 Have you given me points for raising this pr?

yes

**Comment by diyajaiswal11** [comment]
> @diyajaiswal11 since i have raised the issue i would like to work on it

Okay @Vrindagupta6828 , Go ahead.
