### ISSUE TITLE
Add reply section to Comments

### ISSUE THREAD

**Issue by Vrindagupta6828** [diyajaiswal11/Bloggitt#53]
**Is your feature request related to a problem? Please describe.**
The comment section does not have a reply section.

**Describe the solution you'd like**
We can add that

**Comment by diyajaiswal11** [comment]
Would you like to work on this issue @Vrindagupta6828 ?

**Comment by Vrindagupta6828** [comment]
@diyajaiswal11 sure

**Comment by Vrindagupta6828** [comment]
@diyajaiswal11 Have you given me points for raising this pr?

**Comment by diyajaiswal11** [comment]
> @diyajaiswal11 Have you given me points for raising this pr?

yes
