### ISSUE TITLE
Tags for a blog

### ISSUE THREAD

**Issue by SubhradeepSS** [diyajaiswal11/Bloggitt#56]
**Is your feature request related to a problem? Please describe.**
Different tags can be attached to a blog like #blog,#firstblog,etc.

**Describe the solution you'd like**
Adding an extra field `tags` for model `Post` by using [django-taggit](https://django-taggit.readthedocs.io/en/latest/)

**Comment by SubhradeepSS** [comment]
@diyajaiswal11 I want to work on this issue, if it seems fine to you.

**Comment by diyajaiswal11** [comment]
> @diyajaiswal11 I want to work on this issue, if it seems fine to you.

Great idea!! Go ahead @SubhradeepSS
