### ISSUE TITLE
Tag Dictionary

### ISSUE THREAD

**Issue by SubhradeepSS** [diyajaiswal11/Bloggitt#57]
**Is your feature request related to a problem? Please describe.**
Count of each tag used.

**Describe the solution you'd like**
We can have a model storing the count of each tag used so that we can use it for future features like filtering blogs by tags etc.

**Comment by SubhradeepSS** [comment]
@diyajaiswal11 If you think this issue is fine, then I can start working on it.

**Comment by diyajaiswal11** [comment]
> **Is your feature request related to a problem? Please describe.**
> Count of each tag used.
> 
> **Describe the solution you'd like**
> We can have a model storing the count of each tag used so that we can use it for future features like filtering blogs by tags etc.

Sure @SubhradeepSS , go ahead.
