### ISSUE TITLE
Beautify Profile GUI

### ISSUE THREAD

**Issue by Halix267** [diyajaiswal11/Bloggitt#59]
**Is your feature request related to a problem? Please describe.**
Currently the user profile is not looking good

**Describe the solution you'd like**
Adding html ,css and js to make user profile page to look attaractive

**Comment by Halix267** [comment]
@diyajaiswal11 Can i take this

**Comment by diyajaiswal11** [comment]
Sure @Halix267 , go ahead.

**Comment by Halix267** [comment]
@diyajaiswal11 Have you given me points for raising this pr?

**Comment by dollyjain51099** [comment]
I want to work on this issue can u please assign it to me.

**Comment by diyajaiswal11** [comment]
> I want to work on this issue can u please assign it to me.

Go ahead @dollyjain51099
