### ISSUE TITLE
Add  Delete Option in the Post

### ISSUE THREAD

**Issue by Halix267** [diyajaiswal11/Bloggitt#62]
**Is your feature request related to a problem? Please describe.**
Currently if a user want to delete his/her post  he doest not have functionality to delete the post

**Describe the solution you'd like**
Add delete option in the post so that a user can delete his/her post

**Comment by Halix267** [comment]
@diyajaiswal11 Can I work on this

**Comment by dollyjain51099** [comment]
I want to work on this issue can u please assign it to me.
