### ISSUE TITLE
Tag based Blog ListView

### ISSUE THREAD

**Issue by SubhradeepSS** [diyajaiswal11/Bloggitt#64]
**Is your feature request related to a problem? Please describe.**
Clicking on a tag in any post will show all the posts having that tag.

**Describe the solution you'd like**
Having a separate html page which will dynamically render all the posts based on the tag clicked.

**Approach to be followed (optional)**
- creating an endpoint in `urls.py` for the feature
- linking all the tags in existing html pages with the endpoint created
- writing required `html` page code
- writing corresponding view logic in `views.py`

**Comment by diyajaiswal11** [comment]
> **Is your feature request related to a problem? Please describe.**
> Clicking on a tag in any post will show all the posts having that tag.
> 
> **Describe the solution you'd like**
> Having a separate html page which will dynamically render all the posts based on the tag clicked.
> 
> **Approach to be followed (optional)**
> 
> * creating an endpoint in `urls.py` for the feature
> * linking all the tags in existing html pages with the endpoint created
> * writing required `html` page code
> * writing corresponding view logic in `views.py`

Go ahead @SubhradeepSS

**Comment by SubhradeepSS** [comment]
@diyajaiswal11 I guess this issue requires a lot of work to do so it should be labelled as atleast intermediate. What are your views on this?

**Comment by diyajaiswal11** [comment]
> @diyajaiswal11 I guess this issue requires a lot of work to do so it should be labelled as atleast intermediate. What are your views on this?

Already two issues have been raised on the tag feature, so let's keep it beginner only.
