### ISSUE TITLE
Adding Navigation Bar in every page

### ISSUE THREAD

**Issue by rsrkpatwari1234** [diyajaiswal11/Bloggitt#68]
**Is your feature request related to a problem? Please describe.**
Currently, when we got to 'About' page or the profile page, we get stuck as we cannot navigate further.The only option is to move back.

**Describe the solution you'd like**
We should add navigation bars on every page so that the UI is interactive and flexible to navigate

I want to take up this issue,please consider it !!

**Comment by diyajaiswal11** [comment]
Go ahead @rsrkpatwari1234
