### ISSUE TITLE
Add Category option in Blogs

### ISSUE THREAD

**Issue by diyajaiswal11** [diyajaiswal11/Bloggitt#7]
Add categories for blogs. List of categories are:
- Programming/Technology
- Health/Fitness
- Personal
- Fashion 
- Food
- Travel
- Business
- Art
- Other

**Comment by Vrindagupta6828** [comment]
@diyajaiswal11 I want to work on this issue please assign this to me.

**Comment by diyajaiswal11** [comment]
Sure @Vrindagupta6828 , Go ahead.
