### ISSUE TITLE
views.py for upload blog page

### ISSUE THREAD

**Issue by SubhradeepSS** [diyajaiswal11/Bloggitt#71]
**Describe the solution you'd like**
`views.py` code for upload blog page(issue- #8)

**Comment by diyajaiswal11** [comment]
> **Describe the solution you'd like**
> `views.py` code for upload blog page(issue- #8)

Go ahead @SubhradeepSS

**Comment by SubhradeepSS** [comment]
> 
> 
> > **Describe the solution you'd like**
> > `views.py` code for upload blog page(issue- #8)
> 
> Go ahead @SubhradeepSS

Should I start working on the issue right now or after issue #8 is solved?

**Comment by diyajaiswal11** [comment]
> > > **Describe the solution you'd like**
> > > `views.py` code for upload blog page(issue- #8)
> > 
> > 
> > Go ahead @SubhradeepSS
> 
> Should I start working on the issue right now or after issue #8 is solved?

You can starting working on it @SubhradeepSS
