### ISSUE TITLE
Feature request: Dockerfile

### ISSUE THREAD

**Issue by SubhradeepSS** [diyajaiswal11/Bloggitt#75]
**Is your feature request related to a problem? Please describe.**
Create a dockerfile for the project

**Comment by SubhradeepSS** [comment]
@diyajaiswal11 Shall i create a dockerfile for the project?

**Comment by diyajaiswal11** [comment]
> @diyajaiswal11 Shall i create a dockerfile for the project?

Go ahead @SubhradeepSS
