### ISSUE TITLE
Adding contributors in the readme

### ISSUE THREAD

**Issue by m-code12** [diyajaiswal11/Bloggitt#76]
We can add the list of contributors who contributed to this repository similar to this :

![Screenshot (294)](https://user-images.githubusercontent.com/53649201/103304639-2cc5a200-4a2f-11eb-8a6f-24270d66128c.png)

**Comment by m-code12** [comment]
@diyajaiswal11 
I would like to work on this.

**Comment by diyajaiswal11** [comment]
> @diyajaiswal11
> I would like to work on this.

Go ahead @m-code12
