### ISSUE TITLE
Add Upload Blog posts form page

### ISSUE THREAD

**Issue by diyajaiswal11** [diyajaiswal11/Bloggitt#8]
- Create a page upload.html (similar page as that of detail.html) and inside the container add the form to upload a Blog Post. (refer post model)
- On the Navbar add option to upload a Blog Post.
- You have to work on template and urls.py , not on views.py.

**Comment by Poobalan1210** [comment]
I would like to work on this issue

**Comment by diyajaiswal11** [comment]
Sure @Poobalan1210 , Go ahead.

**Comment by TrushaT** [comment]
@diyajaiswal11  pls assign this issue to me.

**Comment by diyajaiswal11** [comment]
> @diyajaiswal11 pls assign this issue to me.

Sure @TrushaT , Go ahead.

**Comment by TrushaT** [comment]
aafter clicking a create post option on navbar, it should render form - that's what you want right ? No backend saving of form ?

**Comment by TrushaT** [comment]
Over here @diyajaiswal11 you mention not to work on views.py so I can create a separate issue for working on views.py?

**Comment by SubhradeepSS** [comment]
@diyajaiswal11 Can u assign me this issue?

**Comment by TrushaT** [comment]
@SubhradeepSS I am working on it .

**Comment by rsrkpatwari1234** [comment]
Hey @diyajaiswal11 !! I want to work on this issue

**Comment by diyajaiswal11** [comment]
> Hey @diyajaiswal11 !! I want to work on this issue

Go ahead @rsrkpatwari1234

**Comment by SubhradeepSS** [comment]
@diyajaiswal11 Shall I create a new issue for working on `views.py` section for the blog upload page, since u mentioned not to work on `views.py` for this issue?

**Comment by diyajaiswal11** [comment]
> @diyajaiswal11 Shall I create a new issue for working on `views.py` section for the blog upload page and start working on it, since u mentioned not to work on `views.py` for this issue?

Go ahead @SubhradeepSS

**Comment by SubhradeepSS** [comment]
@diyajaiswal11 can u assign it to me since there is no PR for 8days?

**Comment by diyajaiswal11** [comment]
> @diyajaiswal11 can u assign it to me since there is no PR for 8days?

Go ahead @SubhradeepSS

**Comment by SubhradeepSS** [comment]
@diyajaiswal11 I think this issue is resolved, so it can be closed i guess.
