### ISSUE TITLE
Slug Field should be autofilled

### ISSUE THREAD

**Issue by diyajaiswal11** [diyajaiswal11/Bloggitt#9]
Currently, on creating a post object, we need to fill the slug field too. The slug field should be automatically generated using the title of the blog post whenever a new post object is created.

**Comment by SubhradeepSS** [comment]
@diyajaiswal11 I was thinking of using django-autoslug - https://pypi.org/project/django-autoslug/ pip package to solve this issue

**Comment by diyajaiswal11** [comment]
> @diyajaiswal11 I was thinking of using django-autoslug - https://pypi.org/project/django-autoslug/ pip package to solve this issue

Hey @SubhradeepSS , instead of installing and using a package, you can directly import slugify in django and use it. I would recommend you to go through it once. :)

**Comment by SubhradeepSS** [comment]
> 
> 
> > @diyajaiswal11 I was thinking of using django-autoslug - https://pypi.org/project/django-autoslug/ pip package to solve this issue
> 
> Hey @SubhradeepSS , instead of installing and using a package, you can directly import slugify in django and use it. I would recommend you to go through it once. :)

Sure. Can u assign me this issue?

**Comment by diyajaiswal11** [comment]
> > > @diyajaiswal11 I was thinking of using django-autoslug - https://pypi.org/project/django-autoslug/ pip package to solve this issue
> > 
> > 
> > Hey @SubhradeepSS , instead of installing and using a package, you can directly import slugify in django and use it. I would recommend you to go through it once. :)
> 
> Sure. Can u assign me this issue?

Sure!

**Comment by SubhradeepSS** [comment]
@diyajaiswal11 i fixed the issue. Should I send the PR now or after Dec 1?

**Comment by diyajaiswal11** [comment]
> @diyajaiswal11 i fixed the issue and opened a PR for the same. Should I reopen it now or after Dec 1?

You can open the pull request now. I'll merge it after 1st so that it's counted for NWOC'20.
